[2023-12-21T15:42:23.874+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:42:23.876+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:42:24.047+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:42:24.049+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:42:24.293+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:42:24.432+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:42:24.433+0000] {taskinstance.py:1361} INFO - Starting attempt 10 of 10
[2023-12-21T15:42:24.495+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:13:27.619896+00:00
[2023-12-21T15:42:24.534+0000] {standard_task_runner.py:57} INFO - Started process 107 to run task
[2023-12-21T15:42:24.638+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:13:27.619896+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/apps/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmpuxhkixdi']
[2023-12-21T15:42:24.654+0000] {standard_task_runner.py:85} INFO - Job 41: Subtask test***
[2023-12-21T15:42:25.058+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:42:25.060+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:42:25.075+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [running]> on host cdaea2bd355d
[2023-12-21T15:42:25.310+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:13:27.619896+00:00' AIRFLOW_CTX_TRY_NUMBER='10' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:13:27.619896+00:00'
[2023-12-21T15:42:25.346+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:42:25.349+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:42:25.383+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:42:25.977+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:42:25.979+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/webscrapinglinkedin/aux-pedreiro.py", line 1, in <module>
[2023-12-21T15:42:25.980+0000] {subprocess.py:93} INFO -     from lib.browser import browser
[2023-12-21T15:42:25.981+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'lib'
[2023-12-21T15:42:25.992+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:42:26.024+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:42:26.041+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T151327, start_date=20231221T154224, end_date=20231221T154226
[2023-12-21T15:42:26.095+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 41 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 107)
[2023-12-21T15:42:26.126+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:42:26.172+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
