[2023-12-21T15:19:03.400+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:19:03.404+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:19:03.449+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:19:03.451+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:19:03.504+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:19:03.520+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [queued]>
[2023-12-21T15:19:03.521+0000] {taskinstance.py:1361} INFO - Starting attempt 5 of 5
[2023-12-21T15:19:03.544+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:13:27.619896+00:00
[2023-12-21T15:19:03.552+0000] {standard_task_runner.py:57} INFO - Started process 1164 to run task
[2023-12-21T15:19:03.557+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:13:27.619896+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dag-webscrappinglinkedin.py', '--cfg-path', '/tmp/tmpu0pbzywn']
[2023-12-21T15:19:03.559+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask test***
[2023-12-21T15:19:03.631+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509
[2023-12-21T15:19:03.632+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:13:27.619896+00:00/task_id=test***'
[2023-12-21T15:19:03.637+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:13:27.619896+00:00 [running]> on host ae1e32dc581d
[2023-12-21T15:19:03.759+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:13:27.619896+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:13:27.619896+00:00'
[2023-12-21T15:19:03.761+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:19:03.763+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/aux-pedreiro.py']
[2023-12-21T15:19:03.780+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:19:06.558+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:19:06.561+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/aux-pedreiro.py", line 1, in <module>
[2023-12-21T15:19:06.565+0000] {subprocess.py:93} INFO -     from ***.dags.lib.browser import browser
[2023-12-21T15:19:06.574+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named '***.dags'
[2023-12-21T15:19:06.791+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:19:06.808+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:19:06.815+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T151327, start_date=20231221T151903, end_date=20231221T151906
[2023-12-21T15:19:06.839+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 32 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 1164)
[2023-12-21T15:19:06.874+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:19:06.898+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
