[2023-12-21T12:58:23.900+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509
[2023-12-21T12:58:23.903+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test***'
[2023-12-21T12:58:23.953+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509
[2023-12-21T12:58:23.954+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test***'
[2023-12-21T12:58:24.007+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-21T12:58:24.024+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-21T12:58:24.025+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-12-21T12:58:24.048+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-20 00:00:00+00:00
[2023-12-21T12:58:24.056+0000] {standard_task_runner.py:57} INFO - Started process 684 to run task
[2023-12-21T12:58:24.061+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'scheduled__2023-12-20T00:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag-webscrappinglinkedin.py', '--cfg-path', '/tmp/tmpfusou3lu']
[2023-12-21T12:58:24.064+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask test***
[2023-12-21T12:58:24.137+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509
[2023-12-21T12:58:24.138+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test***'
[2023-12-21T12:58:24.143+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow scheduled__2023-12-20T00:00:00+00:00 [running]> on host c6e463718549
[2023-12-21T12:58:24.262+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-20T00:00:00+00:00'
[2023-12-21T12:58:24.266+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T12:58:24.269+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/apps/crawler.py']
[2023-12-21T12:58:24.290+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T12:58:24.571+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T12:58:24.572+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/apps/crawler.py", line 3, in <module>
[2023-12-21T12:58:24.573+0000] {subprocess.py:93} INFO -     from selenium import webdriver
[2023-12-21T12:58:24.574+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'selenium'
[2023-12-21T12:58:24.579+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T12:58:24.598+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T12:58:24.604+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231220T000000, start_date=20231221T125824, end_date=20231221T125824
[2023-12-21T12:58:24.628+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 684)
[2023-12-21T12:58:24.676+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T12:58:24.705+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
