[2023-12-21T12:50:30.512+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509
[2023-12-21T12:50:31.471+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test***'
[2023-12-21T12:50:31.669+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509
[2023-12-21T12:50:31.672+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test***'
[2023-12-21T12:50:31.954+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-21T12:50:31.994+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow scheduled__2023-12-20T00:00:00+00:00 [queued]>
[2023-12-21T12:50:31.996+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-21T12:50:32.129+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-20 00:00:00+00:00
[2023-12-21T12:50:32.143+0000] {standard_task_runner.py:57} INFO - Started process 572 to run task
[2023-12-21T12:50:32.152+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'scheduled__2023-12-20T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag-webscrappinglinkedin.py', '--cfg-path', '/tmp/tmp7235js3p']
[2023-12-21T12:50:32.157+0000] {standard_task_runner.py:85} INFO - Job 3: Subtask test***
[2023-12-21T12:50:33.107+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509
[2023-12-21T12:50:33.108+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=scheduled__2023-12-20T00:00:00+00:00/task_id=test***'
[2023-12-21T12:50:33.139+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow scheduled__2023-12-20T00:00:00+00:00 [running]> on host c6e463718549
[2023-12-21T12:50:33.926+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-20T00:00:00+00:00'
[2023-12-21T12:50:33.937+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T12:50:33.940+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/crawler.py']
[2023-12-21T12:50:33.975+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T12:50:34.410+0000] {subprocess.py:93} INFO - python: can't open file '/opt/***/dags/crawler.py': [Errno 2] No such file or directory
[2023-12-21T12:50:34.421+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-12-21T12:50:34.446+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-12-21T12:50:34.457+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231220T000000, start_date=20231221T125031, end_date=20231221T125034
[2023-12-21T12:50:34.500+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 3 for task test*** (Bash command failed. The command returned a non-zero exit code 2.; 572)
[2023-12-21T12:50:34.552+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T12:50:34.588+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
