[2023-12-21T15:53:29.368+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:53:29.374+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:53:29.462+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:53:29.466+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:53:29.653+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:53:29.748+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [queued]>
[2023-12-21T15:53:29.759+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-21T15:53:29.911+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): testairflow> on 2023-12-21 15:53:24.607881+00:00
[2023-12-21T15:53:29.948+0000] {standard_task_runner.py:57} INFO - Started process 270 to run task
[2023-12-21T15:53:29.965+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'scraping-jobs', 'test***', 'manual__2023-12-21T15:53:24.607881+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/webscrapinglinkedin/dag-webscrapinglinkedin.py', '--cfg-path', '/tmp/tmp038ggt0p']
[2023-12-21T15:53:29.975+0000] {standard_task_runner.py:85} INFO - Job 46: Subtask test***
[2023-12-21T15:53:30.376+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509
[2023-12-21T15:53:30.379+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test*** permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=scraping-jobs/run_id=manual__2023-12-21T15:53:24.607881+00:00/task_id=test***'
[2023-12-21T15:53:30.418+0000] {task_command.py:416} INFO - Running <TaskInstance: scraping-jobs.testairflow manual__2023-12-21T15:53:24.607881+00:00 [running]> on host cdaea2bd355d
[2023-12-21T15:53:30.996+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scraping-jobs' AIRFLOW_CTX_TASK_ID='test***' AIRFLOW_CTX_EXECUTION_DATE='2023-12-21T15:53:24.607881+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-21T15:53:24.607881+00:00'
[2023-12-21T15:53:31.001+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-12-21T15:53:31.009+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/***/dags/webscrapinglinkedin/aux-pedreiro.py']
[2023-12-21T15:53:31.057+0000] {subprocess.py:86} INFO - Output:
[2023-12-21T15:53:36.712+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-12-21T15:53:36.728+0000] {subprocess.py:93} INFO -   File "/opt/***/dags/webscrapinglinkedin/aux-pedreiro.py", line 1, in <module>
[2023-12-21T15:53:36.760+0000] {subprocess.py:93} INFO -     from ***.dags.webscrapinglinkedin.browser import browser
[2023-12-21T15:53:36.776+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named '***.dags'
[2023-12-21T15:53:37.166+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-12-21T15:53:37.190+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-12-21T15:53:37.198+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=scraping-jobs, task_id=test***, execution_date=20231221T155324, start_date=20231221T155329, end_date=20231221T155337
[2023-12-21T15:53:37.222+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 46 for task test*** (Bash command failed. The command returned a non-zero exit code 1.; 270)
[2023-12-21T15:53:37.268+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-21T15:53:37.307+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
